# This is a basic workflow to help you get started with Actions

name: vscode

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: Download vs code
      run: ./install_code.sh

    - name: Start server
      run: ./code-server-3.4.1-linux-x86_64/bin/code-server --bind-addr 127.0.0.1:8779 --auth none



    # Runs a set of commands using the runners shell
    - name: Run ngrok
      run: |
        curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
        unzip ngrok-stable-linux-386.zip
        ./ngrok authtoken ${NGROK_TOKEN}
        ./ngrok http 8779
      env:
        CI: true
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

